export { default as MessageBox } from '../..\\components\\MessageBox.vue'
export { default as ActualitySystem } from '../..\\components\\ActualitySystemPage\\ActualitySystem.vue'
export { default as BranchesPage } from '../..\\components\\Branches\\BranchesPage.vue'
export { default as BtnGen } from '../..\\components\\Button\\BtnGen.vue'
export { default as GenericButton } from '../..\\components\\Button\\GenericButton.vue'
export { default as DashboardPage } from '../..\\components\\Dashboard\\DashboardPage.vue'
export { default as ColumnConfigPage } from '../..\\components\\ColumnConfig\\ColumnConfigPage.vue'
export { default as GenericInvoiceFilteringModalPage } from '../..\\components\\GenericInvoiceFilteringModal\\GenericInvoiceFilteringModalPage.vue'
export { default as GenericInvoiceItemModalPage } from '../..\\components\\GenericInvoiceItemModal\\GenericInvoiceItemModalPage.vue'
export { default as GenericPrepareTablePage } from '../..\\components\\GenericPrepareTable\\GenericPrepareTablePage.vue'
export { default as GenericTablePage } from '../..\\components\\GenericTable\\GenericTablePage.vue'
export { default as GenericTranslatePage } from '../..\\components\\GenericTranslate\\GenericTranslatePage.vue'
export { default as GenericCheckBox } from '../..\\components\\Generics\\GenericCheckBox.vue'
export { default as GenericImageUpload } from '../..\\components\\Generics\\GenericImageUpload.vue'
export { default as GenericInput } from '../..\\components\\Generics\\GenericInput.vue'
export { default as GenericLookUp } from '../..\\components\\Generics\\GenericLookUp.vue'
export { default as GenericMultipleSelect } from '../..\\components\\Generics\\GenericMultipleSelect.vue'
export { default as GenericPagination } from '../..\\components\\Generics\\GenericPagination.vue'
export { default as GenericInputDatePage } from '../..\\components\\InputDate\\GenericInputDatePage.vue'
export { default as InternalInvoice } from '../..\\components\\InternalInvoices\\InternalInvoice.vue'
export { default as InternalViabranchreceive } from '../..\\components\\InternalInvoices\\InternalViabranchreceive.vue'
export { default as PrepareInternalInvoiceNew } from '../..\\components\\InternalInvoices\\PrepareInternalInvoiceNew.vue'
export { default as PrepareInternalInvoiceNewDevice } from '../..\\components\\InternalInvoices\\PrepareInternalInvoiceNewDevice.vue'
export { default as PrepareReceiveInvoiceNew } from '../..\\components\\InternalInvoices\\PrepareReceiveInvoiceNew.vue'
export { default as ExpenseInvoicePage } from '../..\\components\\Invoices\\ExpenseInvoicePage.vue'
export { default as InputFromProductionCompanyPage } from '../..\\components\\Invoices\\InputFromProductionCompanyPage.vue'
export { default as InputReturnPage } from '../..\\components\\Invoices\\InputReturnPage.vue'
export { default as InputToServiceInvoicePage } from '../..\\components\\Invoices\\InputToServiceInvoicePage.vue'
export { default as MakeBillPage } from '../..\\components\\Invoices\\MakeBillPage.vue'
export { default as MarketSalesInvoice } from '../..\\components\\Invoices\\MarketSalesInvoice.vue'
export { default as OpenControlPageNewPage } from '../..\\components\\Invoices\\OpenControlPageNewPage.vue'
export { default as OutputProductionInvoice } from '../..\\components\\Invoices\\OutputProductionInvoice.vue'
export { default as OutputProductionReturn } from '../..\\components\\Invoices\\OutputProductionReturn.vue'
export { default as OutputToProductionCompanyPage } from '../..\\components\\Invoices\\OutputToProductionCompanyPage.vue'
export { default as OutputToProductionCompanyReturnPage } from '../..\\components\\Invoices\\OutputToProductionCompanyReturnPage.vue'
export { default as OutputToPrOrderPage } from '../..\\components\\Invoices\\OutputToPrOrderPage.vue'
export { default as OutputToPrOrderReturnPage } from '../..\\components\\Invoices\\OutputToPrOrderReturnPage.vue'
export { default as OutputToServiceInvoicePage } from '../..\\components\\Invoices\\OutputToServiceInvoicePage.vue'
export { default as PrepareExpenseInvoicePage } from '../..\\components\\Invoices\\prepareExpenseInvoicePage.vue'
export { default as PrepareInputFromProductionCompanyNewPage } from '../..\\components\\Invoices\\PrepareInputFromProductionCompanyNewPage.vue'
export { default as PrepareInputReturnNewPage } from '../..\\components\\Invoices\\PrepareInputReturnNewPage.vue'
export { default as PrepareInputToServiceInvoicePage } from '../..\\components\\Invoices\\PrepareInputToServiceInvoicePage.vue'
export { default as PrepareOutputToEquipmentPage } from '../..\\components\\Invoices\\PrepareOutputToEquipmentPage.vue'
export { default as PrepareOutputToEquipmentReturnPage } from '../..\\components\\Invoices\\PrepareOutputToEquipmentReturnPage.vue'
export { default as PrepareOutputToProductionCompanyNewPage } from '../..\\components\\Invoices\\prepareOutputToProductionCompanyNewPage.vue'
export { default as PrepareOutputToProductionCompanyReturnNewPage } from '../..\\components\\Invoices\\PrepareOutputToProductionCompanyReturnNewPage.vue'
export { default as PrepareOutputToPrOrderPage } from '../..\\components\\Invoices\\PrepareOutputToPrOrderPage.vue'
export { default as PrepareOutputToPrOrderReturnPage } from '../..\\components\\Invoices\\PrepareOutputToPrOrderReturnPage.vue'
export { default as PrepareOutputToPrOrderSimple } from '../..\\components\\Invoices\\PrepareOutputToPrOrderSimple.vue'
export { default as PrepareOutputToServiceInvoicePage } from '../..\\components\\Invoices\\PrepareOutputToServiceInvoicePage.vue'
export { default as PrepareProductionInvoiceNewPage } from '../..\\components\\Invoices\\PrepareProductionInvoiceNewPage.vue'
export { default as PreparePurchaseInvoiceNewPage } from '../..\\components\\Invoices\\PreparePurchaseInvoiceNewPage.vue'
export { default as PreparePurchaseServiceInvoiceNewPage } from '../..\\components\\Invoices\\PreparePurchaseServiceInvoiceNewPage.vue'
export { default as PrepareSaleInvoiceNewPage } from '../..\\components\\Invoices\\PrepareSaleInvoiceNewPage.vue'
export { default as PrepareSaleServiceInvoiceNewPage } from '../..\\components\\Invoices\\PrepareSaleServiceInvoiceNewPage.vue'
export { default as PrepareSalesReturnNewPage } from '../..\\components\\Invoices\\PrepareSalesReturnNewPage.vue'
export { default as PrepareSimpleProductionInvoiceManualPage } from '../..\\components\\Invoices\\PrepareSimpleProductionInvoiceManualPage.vue'
export { default as PrepareSimpleProductionInvoicePage } from '../..\\components\\Invoices\\PrepareSimpleProductionInvoicePage.vue'
export { default as ProductionByPackagePage } from '../..\\components\\Invoices\\ProductionByPackagePage.vue'
export { default as ProductionForQrCodeListPage } from '../..\\components\\Invoices\\ProductionForQrCodeListPage.vue'
export { default as ProductionInvoicePage } from '../..\\components\\Invoices\\ProductionInvoicePage.vue'
export { default as PurchaseInvoisePage } from '../..\\components\\Invoices\\PurchaseInvoisePage.vue'
export { default as PurchaseServiceInvoicePage } from '../..\\components\\Invoices\\PurchaseServiceInvoicePage.vue'
export { default as SaleInvoicePage } from '../..\\components\\Invoices\\SaleInvoicePage.vue'
export { default as SaleServiceInvoicePage } from '../..\\components\\Invoices\\SaleServiceInvoicePage.vue'
export { default as SalesReturnPage } from '../..\\components\\Invoices\\SalesReturnPage.vue'
export { default as SimpleProductionInvoicePage } from '../..\\components\\Invoices\\SimpleProductionInvoicePage.vue'
export { default as MainList } from '../..\\components\\Lists\\MainList.vue'
export { default as LoadingPage } from '../..\\components\\Loading\\LoadingPage.vue'
export { default as LoginPage } from '../..\\components\\Login\\LoginPage.vue'
export { default as ItemSearchList } from '../..\\components\\main\\ItemSearchList.vue'
export { default as LanguageSelector } from '../..\\components\\main\\LanguageSelector.vue'
export { default as MainHeader } from '../..\\components\\main\\MainHeader.vue'
export { default as SearchBar } from '../..\\components\\main\\SearchBar.vue'
export { default as MenuSettings } from '../..\\components\\MenuSettings\\MenuSettings.vue'
export { default as BatchesList } from '../..\\components\\Productions\\BatchesList.vue'
export { default as BatchProcess } from '../..\\components\\Productions\\BatchProcess.vue'
export { default as BatchProcessStages } from '../..\\components\\Productions\\BatchProcessStages.vue'
export { default as BatchUnions } from '../..\\components\\Productions\\BatchUnions.vue'
export { default as ColorDepth } from '../..\\components\\Productions\\ColorDepth.vue'
export { default as ColorsList } from '../..\\components\\Productions\\ColorsList.vue'
export { default as ColorVariant } from '../..\\components\\Productions\\ColorVariant.vue'
export { default as ColorVariantRecipeStage } from '../..\\components\\Productions\\ColorVariantRecipeStage.vue'
export { default as ColorVariantRecipeStageChild } from '../..\\components\\Productions\\ColorVariantRecipeStageChild.vue'
export { default as ColorVariantRecipeStageGroup } from '../..\\components\\Productions\\ColorVariantRecipeStageGroup.vue'
export { default as ColorVariantRecipeStagePicture } from '../..\\components\\Productions\\ColorVariantRecipeStagePicture.vue'
export { default as DesignsList } from '../..\\components\\Productions\\DesignsList.vue'
export { default as DesignTypes } from '../..\\components\\Productions\\DesignTypes.vue'
export { default as DesignVariants } from '../..\\components\\Productions\\DesignVariants.vue'
export { default as EquipmentsRealTimeStatus } from '../..\\components\\Productions\\EquipmentsRealTimeStatus.vue'
export { default as OrderProductionTypes } from '../..\\components\\Productions\\OrderProductionTypes.vue'
export { default as PackagingList } from '../..\\components\\Productions\\PackagingList.vue'
export { default as PlanningTypes } from '../..\\components\\Productions\\PlanningTypes.vue'
export { default as PrepareBatchNew } from '../..\\components\\Productions\\PrepareBatchNew.vue'
export { default as PrepareBatchProcess } from '../..\\components\\Productions\\PrepareBatchProcess.vue'
export { default as PrepareBatchProcessStage } from '../..\\components\\Productions\\PrepareBatchProcessStage.vue'
export { default as PrepareBatchUnionsNew } from '../..\\components\\Productions\\PrepareBatchUnionsNew.vue'
export { default as PrepareColor } from '../..\\components\\Productions\\PrepareColor.vue'
export { default as PrepareColorDepth } from '../..\\components\\Productions\\PrepareColorDepth.vue'
export { default as PrepareColorVariant } from '../..\\components\\Productions\\PrepareColorVariant.vue'
export { default as PrepareColorVariantRecipeStage } from '../..\\components\\Productions\\PrepareColorVariantRecipeStage.vue'
export { default as PrepareColorVariantRecipeStageChild } from '../..\\components\\Productions\\PrepareColorVariantRecipeStageChild.vue'
export { default as PrepareColorVariantRecipeStageGroup } from '../..\\components\\Productions\\PrepareColorVariantRecipeStageGroup.vue'
export { default as PrepareColorVariantRecipeStagePicture } from '../..\\components\\Productions\\PrepareColorVariantRecipeStagePicture.vue'
export { default as PrepareDesign } from '../..\\components\\Productions\\PrepareDesign.vue'
export { default as PrepareDesignType } from '../..\\components\\Productions\\PrepareDesignType.vue'
export { default as PrepareDesignVariant } from '../..\\components\\Productions\\PrepareDesignVariant.vue'
export { default as PrepareOrderProductionType } from '../..\\components\\Productions\\PrepareOrderProductionType.vue'
export { default as PreparePackaging } from '../..\\components\\Productions\\PreparePackaging.vue'
export { default as PreparePlanningType } from '../..\\components\\Productions\\PreparePlanningType.vue'
export { default as PrepareProductProductionType } from '../..\\components\\Productions\\PrepareProductProductionType.vue'
export { default as PrepareSewModel } from '../..\\components\\Productions\\PrepareSewModel.vue'
export { default as PrepareSewModelOperationName } from '../..\\components\\Productions\\PrepareSewModelOperationName.vue'
export { default as PrepareSewModelVariantsSize } from '../..\\components\\Productions\\PrepareSewModelVariantsSize.vue'
export { default as PrepareStage } from '../..\\components\\Productions\\PrepareStage.vue'
export { default as ProductionAdditionTable } from '../..\\components\\Productions\\ProductionAdditionTable.vue'
export { default as ProductProductionTypes } from '../..\\components\\Productions\\ProductProductionTypes.vue'
export { default as SewModel } from '../..\\components\\Productions\\SewModel.vue'
export { default as SewModelOperationName } from '../..\\components\\Productions\\SewModelOperationName.vue'
export { default as SewModelVariantsSize } from '../..\\components\\Productions\\SewModelVariantsSize.vue'
export { default as SewOrderOnlineStatus } from '../..\\components\\Productions\\SewOrderOnlineStatus.vue'
export { default as StagesList } from '../..\\components\\Productions\\StagesList.vue'
export { default as GenericSelect } from '../..\\components\\Select\\GenericSelect.vue'
export { default as SessionsPage } from '../..\\components\\Sessions\\SessionsPage.vue'
export { default as GenericLogisticsCalculationPage } from '../..\\components\\Generics\\GenericLogisticsCalculation\\GenericLogisticsCalculationPage.vue'
export { default as GenericSubPrepareTablePage } from '../..\\components\\Generics\\GenericSubPrepareTable\\GenericSubPrepareTablePage.vue'
export { default as GenericSubPrepareTableTooPage } from '../..\\components\\Generics\\GenericSubPrepareTableToo\\GenericSubPrepareTableTooPage.vue'
export { default as EndScaleBox } from '../..\\components\\Invoices\\ScaleBoxs\\EndScaleBox.vue'
export { default as ScaleBox } from '../..\\components\\Invoices\\ScaleBoxs\\ScaleBox.vue'
export { default as ScaleBoxGenericTable } from '../..\\components\\Invoices\\ScaleBoxs\\ScaleBoxGenericTable.vue'
export { default as CheckRealCountBarcodePage } from '../..\\components\\Orders\\CheckRealCountBarcodePage\\CheckRealCountBarcodePage.vue'
export { default as DyeingsPage } from '../..\\components\\Orders\\Dyeings\\DyeingsPage.vue'
export { default as ProductionOrderplannigs } from '../..\\components\\Orders\\ProductionOrderPlannigs\\ProductionOrderplannigs.vue'
export { default as ProductionOrderPage } from '../..\\components\\Orders\\ProductionOrderPage\\ProductionOrderPage.vue'
export { default as PurchaseOrderPage } from '../..\\components\\Orders\\PurchaseOrderpage\\PurchaseOrderPage.vue'
export { default as SalesOrderpage } from '../..\\components\\Orders\\SalesOrderpage\\SalesOrderpage.vue'
export { default as BandsPage } from '../..\\components\\Reports\\BandsPage\\BandsPage.vue'
export { default as BatchReportsPage } from '../..\\components\\Reports\\BatchReportsPage\\BatchReportsPage.vue'
export { default as BatchStagesReport } from '../..\\components\\Reports\\BatchStagesReport\\BatchStagesReport.vue'
export { default as BranchProductsStockReportByLogic } from '../..\\components\\Reports\\BranchProductsStockReportByLogic\\BranchProductsStockReportByLogic.vue'
export { default as GradePage } from '../..\\components\\Reports\\GradePage\\GradePage.vue'
export { default as InputStockDetailReport } from '../..\\components\\Reports\\InputStockDetailReport\\InputStockDetailReport.vue'
export { default as InvoiceReportsPage } from '../..\\components\\Reports\\InvoiceReportsPage\\InvoiceReportsPage.vue'
export { default as PersonEquipmentsPage } from '../..\\components\\Reports\\PersonEquipmentsPage\\PersonEquipmentsPage.vue'
export { default as SewBandEquipments } from '../..\\components\\Reports\\SewBandsEquipments\\SewBandEquipments.vue'
export { default as SewModelReport } from '../..\\components\\Reports\\SewModelReport\\SewModelReport.vue'
export { default as TransactionDetailReportPage } from '../..\\components\\Reports\\TransactionDetailReportPage\\TransactionDetailReportPage.vue'
export { default as PageTable } from '../..\\components\\Reports\\TransactionReports\\PageTable.vue'
export { default as SummaryReportPage1 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage1.vue'
export { default as SummaryReportPage2 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage2.vue'
export { default as SummaryReportPage3 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage3.vue'
export { default as SummaryReportPage4 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage4.vue'
export { default as SummaryReportPage5 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage5.vue'
export { default as SummaryReportPage6 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage6.vue'
export { default as SummaryReportPage7 } from '../..\\components\\Reports\\TransactionReports\\SummaryReportPage7.vue'
export { default as TransactionReportsPage } from '../..\\components\\Reports\\TransactionReports\\TransactionReportsPage.vue'
export { default as TransactionSaldoReport } from '../..\\components\\Reports\\TransactionSaldoReport\\TransactionSaldoReport.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
